update readme.md generation

diff --git a/pc b/pc
--- a/pc
+++ b/pc
@@ -169,8 +169,9 @@ setup_files () {
         cp readme.md readme.bak.md &>/dev/null
         echo "# $name version $version" >readme.md
         echo -e "\n---\n" >>readme.md
-        echo '```bash\n`' >>readme.md
-        echo "## $detail" >>readme.md
+        echo "## $detail\n" >>readme.md
+        echo '```bash\n' >>readme.md
+        echo "$sample_pre_commit_template" >>readme.md
         echo '```\n' >>readme.md
     }
     cp .gitignore .gitignore.bak &>/dev/null
@@ -219,41 +220,37 @@ all_checkups () {
     yaml_checkup
 }
 check_args () {
-    echo "arg 1 ... $1"
-    if [ "$1" ]; then
-        case "$1" in
-            init|-i|--init)
-                all_checkups
-                exit 0
-                ;;
+    case "$arg1" in
+        init|-i|--init)
+            all_checkups
+            exit 0
+            ;;
 
-            reset|-r|--reset)
-                echo ''
-                echo '-> pc - reset initial repo files'
-                setup_files
-                exit 0
-                ;;
+        reset|-r|--reset)
+            echo ''
+            echo '-> pc - reset initial repo files'
+            setup_files
+            exit 0
+            ;;
 
-            version|-v|--version)
-                echo "$description"
-                exit 0
-                ;;
+        version|-v|--version)
+            echo "$description"
+            exit 0
+            ;;
 
-            help|-h|--help)
-                echo "$pre_commit_instructions"
-                exit 0
-                ;;
+        help|-h|--help)
+            echo "$pre_commit_instructions"
+            exit 0
+            ;;
 
-            *)
-                echo "Invalid option: $1"
-                echo ""
-                echo "$pre_commit_usage"
-                exit 2
-        esac
-    fi
+        *)
+            echo "Invalid option: $1"
+            echo ""
+            echo "$pre_commit_usage"
+            exit 2
+    esac
 }
 main_loop () {
-    check_args
     pre-commit autoupdate
     if [[ $? != 0 ]]; then
         all_checkups
@@ -262,7 +259,12 @@ main_loop () {
     fi
 }
 
-main_loop
+if [[ -n "$1" ]]; then
+    arg1="$1"
+    check_args
+else
+    main_loop
+fi
 
 ###############################################################################
 # References:
