testing

diff --git a/pc b/pc
--- a/pc
+++ b/pc
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/usr/bin/env zsh
 
 ###############################################################################
 # pc : pre-commit repo automation for macOS (version 1.2.1)
@@ -55,43 +55,41 @@ ge "This script name: $_self"
 ge "The script path is: $bin_path"
 ge "The active repo is: $here"
 
-
-echo -e "\n\n\n\n\n\n\n\n\n\n\n\n${ATTN}test xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx${RESET}"
+echo -e "\n\n\n\n\n\n\n\n\n\n\n\n${ATTN}test"
+echo -e "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx${RESET}"
 ce "$CANARY" "_self xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
 me "main xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
 we "warn xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
 ge "green xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
 pe "purple xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
 
-
-
 exit 0
 ###############################################################################
 # Install prerequisites as needed
 #   brew, git, hub, pipenv, pre-commit
-prereqs_checkup () {
-    brew_checkup () {
+prereqs_checkup() {
+    brew_checkup() {
         which -s brew &>/dev/null
-        if [[ $? != 0 ]] ; then
+        if [[ $? != 0 ]]; then
             # Install Homebrew
             echo 'Homebrew is required but not installed. Installing latest version ...'
             echo ''
             xcode-select --install &>/dev/null
             ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
             which -s brew &>/dev/null
-            if [[ $? != 0 ]] ; then
+            if [[ $? != 0 ]]; then
                 echo 'Homebrew is required but the installation failed. Please check your internet connection and password (if needed) and run this program again. Exiting ...'
                 echo ''
                 exit 1
             else
-                echo `brew --version | tail -n +1 | head -1`' installed ... continuing with setup ...'
+                echo $(brew --version | tail -n +1 | head -1)' installed ... continuing with setup ...'
                 echo ''
             fi
         fi
         brew update &>/dev/null
         brew doctor &>/dev/null
     }
-    git_checkup () {
+    git_checkup() {
         which -s git &>/dev/null
         if [[ $? != 0 ]]; then
             echo 'Git is required but not installed. Installing latest version ...'
@@ -103,13 +101,13 @@ prereqs_checkup () {
                 echo ''
                 exit 1
             else
-                echo `git --version | tail -n +1 | head -1`' installed ... continuing with setup ...'
+                echo $(git --version | tail -n +1 | head -1)' installed ... continuing with setup ...'
                 echo ''
             fi
-        brew update git &>/dev/null
+            brew update git &>/dev/null
         fi
     }
-    hub_checkup () {
+    hub_checkup() {
         which -s hub &>/dev/null
         if [[ $? != 0 ]]; then
             echo 'Hub is required but not installed. Installing latest version ...'
@@ -121,13 +119,13 @@ prereqs_checkup () {
                 echo ''
                 exit 1
             else
-                echo `hub --version | grep hub`' installed ... continuing with setup ...'
+                echo $(hub --version | grep hub)' installed ... continuing with setup ...'
                 echo ''
             fi
             brew update hub &>/dev/null
         fi
     }
-    pipenv_checkup () {
+    pipenv_checkup() {
         which -s pipenv &>/dev/null
         if [[ $? != 0 ]]; then
             echo 'Pipenv is required but not installed. Installing latest version ...'
@@ -139,13 +137,13 @@ prereqs_checkup () {
                 echo ''
                 exit 1
             else
-                echo `pipenv --version`' installed ... continuing with setup ...'
+                echo $(pipenv --version)' installed ... continuing with setup ...'
                 echo ''
             fi
-        brew update pipenv &>/dev/null
+            brew update pipenv &>/dev/null
         fi
     }
-    pre_commit_checkup () {
+    pre_commit_checkup() {
         which -s pre-commit &>/dev/null
         if [[ $? != 0 ]]; then
             brew install pre-commit &>/dev/null
@@ -155,7 +153,7 @@ prereqs_checkup () {
                 echo ''
                 exit 1
             else
-                echo `pre-commit --version`' installed ... continuing with pre-commit setup'
+                echo $(pre-commit --version)' installed ... continuing with pre-commit setup'
                 echo ''
                 # use my sample template instead of `pre-commit sample-config`
                 echo "$sample_settings_template" >.pre-commit-template.yaml
@@ -176,12 +174,12 @@ prereqs_checkup () {
 }
 ###############################################################################
 # Setup Repo - git, github remote, pipenv install, pre-commit config
-readme_md () {
+readme_md() {
     # Generate default README.md
     cp -f README.md bak/README.bak.md &>/dev/null
     echo "# $name version $version" >README.md
     echo "\n$badges\n" >>README.md
-    echo `date +"Last update: %m-%d-%Y | %T"` >>README.md
+    echo $(date +"Last update: %m-%d-%Y | %T") >>README.md
     echo -e "\n---\n" >>README.md
     echo "## $detail\n" >>README.md
     echo '```bash\n' >>README.md
@@ -192,9 +190,9 @@ readme_md () {
     tree >>README.md
     echo '```\n' >>README.md
 }
-yaml_checkup () {
+yaml_checkup() {
     # pre-commit yaml: check for template, backup config, update new config
-    yaml_backup () {
+    yaml_backup() {
         if [ -r ".pre-commit-config.yaml" ]; then
             cp -f .pre-commit-config.yaml bak/.pre-commit-config.yaml.bak
             error_code=$?
@@ -206,7 +204,7 @@ yaml_checkup () {
             fi
         fi
     }
-    yaml_config () {
+    yaml_config() {
         # copy template to current config file
         readme_md
         cat .pre-commit-template.yaml >.pre-commit-config.yaml
@@ -229,8 +227,8 @@ yaml_checkup () {
             echo -e "\nPre-commit successfully updated your configuration."
             git add --all &>/dev/null
             pre-commit &>/dev/null # catch formatting fixes
-            git add --all # again ... after formatting ...
-            pre-commit # again ... after formatting ...
+            git add --all          # again ... after formatting ...
+            pre-commit             # again ... after formatting ...
         fi
     }
 
@@ -247,8 +245,8 @@ yaml_checkup () {
     yaml_backup
     yaml_config
 }
-setup_files () {
-    which_copy () {
+setup_files() {
+    which_copy() {
         # backup previous and create default file
         if [ -r "$file_bak" ]; then
             cp -f $file_bak bak/$file_bak.bak &>/dev/null
@@ -272,7 +270,7 @@ setup_files () {
         echo "$sample_settings_template" >.pre-commit-template.yaml
     fi
 }
-git_repo () {
+git_repo() {
     mkdir -p bak &>/dev/null
     git status &>/dev/null
     if [[ $? != 0 ]]; then
@@ -302,63 +300,64 @@ git_repo () {
     # git initial commit
     git add --all &>/dev/null
     pre-commit &>/dev/null # catch formatting fixes
-    git add --all # again ... after formatting ...
+    git add --all          # again ... after formatting ...
     git commit -m 'initial commit'
     git push --set-upstream origin master
     git status
     git remote -v
 }
-all_checkups () {
+all_checkups() {
     prereqs_checkup
     setup_files
     git_repo
     yaml_checkup
 }
-check_args () {
+check_args() {
     case "$arg1" in
-        init|-i|--init)
-            all_checkups
-            exit 0
-            ;;
+    init | -i | --init)
+        all_checkups
+        exit 0
+        ;;
 
-        reset|-r|--reset)
-            echo ''
-            echo '-> pc - reset initial repo files'
-            setup_files
-            exit 0
-            ;;
+    reset | -r | --reset)
+        echo ''
+        echo '-> pc - reset initial repo files'
+        setup_files
+        exit 0
+        ;;
 
-        version|-v|--version)
-            echo "$description"
-            exit 0
-            ;;
+    version | -v | --version)
+        echo "$description"
+        exit 0
+        ;;
 
-        help|-h|--help)
-            echo "$program_instructions"
-            exit 0
-            ;;
+    help | -h | --help)
+        echo "$program_instructions"
+        exit 0
+        ;;
 
-        commit|-m)
-            if [[ $arg2 != 0 ]]; then
-                yaml_checkup
-                git add --all
-                git commit -m "$arg2"
-                git push
-                exit 0
-            else
-                echo "You must specify a commit message to perform a commit."
-                echo ""
-                exit 2
-            fi
-            ;;
-        *)
-            echo "Invalid option: $arg1"
+    commit | -m)
+        if [[ $arg2 != 0 ]]; then
+            yaml_checkup
+            git add --all
+            git commit -m "$arg2"
+            git push
+            exit 0
+        else
+            echo "You must specify a commit message to perform a commit."
             echo ""
-            echo "$program_usage"
             exit 2
+        fi
+        ;;
+    *)
+        echo "Invalid option: $arg1"
+        echo ""
+        echo "$program_usage"
+        exit 2
+        ;;
     esac
 }
-main_loop () {
+main_loop() {
     git status &>/dev/null
     if [[ $? != 0 ]]; then
         all_checkups
